### ISSUE TITLE
Error: Could not detect buildpack

### ISSUE THREAD

**Issue by IanVaughan** [jasonheecs/heroku-vim#10]
Get this error:
```bash
 !     Could not detect buildpack https://github.com/jasonheecs/her
```

When this is in `app.json`
```json
{
  "buildpacks": [
    { "url": "https://github.com/jasonheecs/heroku-vim" }
```

Same as https://github.com/naaman/heroku-vim/issues/7

**Comment by jasonheecs** [comment]
Hi, this is a [heroku plugin](https://devcenter.heroku.com/articles/using-cli-plugins), not a buildpack.

This plugin extends the Heroku cli to allow for one to connect to an app and use vim.

**Comment by IanVaughan** [comment]
Sorry, many thanks!
